<!DOCTYPE html>
<html lang='en'>

<head>
<meta charset='utf-8'>

<style>

	ul {
		list-style-type: none;
		}
		
	li {
		display: inline;
		font-size: 1.5em;
		font-family: Arial;
	}

</style>

</head>

<body>

	<ul>
		<li><a href='Task1.php'>Task1</a></li>
		<li><a href='Task2.php'>Task2</a></li>
		<li><a href='Task3.php'>Task3</a></li>
		<li><a href='Task4.php'>Task4</a></li>
		<li><a href='Task5.php'>Task5</a></li>
		<li><a href='Task6.php'>Task6</a></li>
	</ul>

</body>

</html>
